<?php
ClassLoader::Get()->registerClass(__DIR__.'/StreamLoop.class.php');
ClassLoader::Get()->registerClass(__DIR__.'/StreamLoop_Exception.class.php');
ClassLoader::Get()->registerClass(__DIR__.'/StreamLoop_AHandler.class.php');
ClassLoader::Get()->registerClass(__DIR__.'/StreamLoop_HTTPS.class.php');
ClassLoader::Get()->registerClass(__DIR__.'/StreamLoop_HTTPS_ICallback.interface.php');
ClassLoader::Get()->registerClass(__DIR__.'/StreamLoop_UDP.class.php');
ClassLoader::Get()->registerClass(__DIR__.'/StreamLoop_UDP_DrainForward.class.php');
ClassLoader::Get()->registerClass(__DIR__.'/StreamLoop_UDP_DrainBackward.class.php');
ClassLoader::Get()->registerClass(__DIR__.'/StreamLoop_UDP_ICallback.interface.php');
ClassLoader::Get()->registerClass(__DIR__.'/StreamLoop_AWebSocket.class.php');
ClassLoader::Get()->registerClass(__DIR__.'/StreamLoop_WebSocket.class.php');
ClassLoader::Get()->registerClass(__DIR__.'/StreamLoop_WebSocket_ICallback.interface.php');
ClassLoader::Get()->registerClass(__DIR__.'/StreamLoop_ATimer.class.php');
ClassLoader::Get()->registerClass(__DIR__.'/StreamLoop_Timer.class.php');
ClassLoader::Get()->registerClass(__DIR__.'/StreamLoop_Timer_ICallback.interface.php');